/*
 * generated by Xtext 2.18.0.M3
 */
package no.tdt4250.project


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AntlrRuntimeModule extends AbstractAntlrRuntimeModule {
}
