grammar no.tdt4250.project.Covilang with no.tdt4250.project.Antlr

import "http://www.tdt4250.no/project/Antlr" as Antlr
generate covilang "http://www.tdt4250.no/project/Covilang" 

CoviFile
	: from=StructureFrom to=StructureTo rule+=Rule*
	;

StructureFrom
	: 'from' importURI=STRING
	;
	
StructureTo
	: 'to' importURI=STRING
	| 'multi-paradigm' 'to' paradigm+=ParadigmInclude+
	;
	
ParadigmInclude
	: paradigm=ID importURI=STRING
	;
	
Rule
	: 'Test:' name=ID test=[Antlr::grammarDecl]
	;