/*
 * generated by Xtext 2.18.0.M3
 */
package no.tdt4250.project


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CovilangStandaloneSetup extends CovilangStandaloneSetupGenerated {

	def static void doSetup() {
		new CovilangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
