/*
 * generated by Xtext 2.18.0.M3
 */
package no.tdt4250.project.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CovilangValidator extends AbstractCovilangValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					CovilangPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
