/*
 * generated by Xtext 2.18.0.M3
 */
package no.tdt4250.project.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class CovilangScopeProvider extends AbstractCovilangScopeProvider {

}
