/*
 * generated by Xtext 2.18.0.M3
 */
package no.tdt4250.project.ide

import com.google.inject.Guice
import no.tdt4250.project.AntlrRuntimeModule
import no.tdt4250.project.AntlrStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AntlrIdeSetup extends AntlrStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AntlrRuntimeModule, new AntlrIdeModule))
	}
	
}
